// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";// Carrega as variaveis do .env, permite que encontre as variáveis
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma", // Schema está nesse arquivo
  migrations: {
    path: "prisma/migrations", // Define onde o Prisma armazenará as Migrations
  },
  datasource: {
    url: process.env["DATABASE_URL"], // URL de conexão com o banco de dados vem deste caminho
  },
});
